package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/rupam_joshi/star_wars/graph/model"
)

// SaveSearchResult is the resolver for the saveSearchResult field.
func (r *mutationResolver) SaveSearchResult(ctx context.Context, result model.CharacterResult) (*model.Character, error) {
	return r.Service.SaveSearchResult(result)
}

// SearchCharacter is the resolver for the searchCharacter field.
func (r *queryResolver) SearchCharacter(ctx context.Context, name string) (*model.Character, error) {
	return r.Service.GetCharacter(name)
}

// GetSavedResults is the resolver for the getSavedResults field.
func (r *queryResolver) GetSavedResults(ctx context.Context) ([]*model.Character, error) {
	return r.Service.GetAllSavedCharacters()
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
