// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	ID       *string   `json:"id,omitempty"`
	Name     string    `json:"name"`
	Films    []*string `json:"films"`
	Vehicles []*string `json:"Vehicles"`
}

type CharacterResult struct {
	ID       *string   `json:"id,omitempty"`
	Name     string    `json:"name"`
	Films    []*string `json:"films"`
	Vehicles []*string `json:"Vehicles"`
}

type Mutation struct {
}

type Query struct {
}
