// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	Name     string   `json:"name"`
	Films    []string `json:"films,omitempty"`
	Vehicles []string `json:"Vehicles,omitempty"`
	SavedAt  *string  `json:"SavedAt,omitempty"`
}

type FavoriteCharacter struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Films    []string `json:"films,omitempty"`
	Vehicles []string `json:"Vehicles,omitempty"`
	SavedAt  string   `json:"SavedAt"`
}

type Mutation struct {
}

type Query struct {
}
